title:              "프로이직러 Mara"
tagline:            "평생직장NO,평생직업YES!"
email:              "somikim1127@naver.com"
description:        "7년 동안 5개 회사에서 근무했습니다. 스타트업에서 마케팅을 하고 있습니다."
author:             "Mara"
baseurl:            "/"
url:                "https://mara.kim"
locale:             "ko_KR"
thumbnail:          "/img/posts/00/00_T.jpg"
cover:              "/img/posts/00/00_Back.jpg"

# Social Profiles
linkedin_username:  somi-kim-884bb1b7
facebook_username:  marakim1127

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate
# 블로그 disqus shortname
disqus:
  shortname: mara-kim
